export const FETCH_FINDINGS_REQUEST = "FETCH_FINDINGS_REQUEST";
export const FETCH_FINDINGS_SUCCESS = "FETCH_FINDINGS_SUCCESS";
export const FETCH_FINDINGS_FAILURE = "FETCH_FINDINGS_FAILURE";

export const SET_SELECTED_FINDING = "SET_SELECTED_FINDING"; 
export const UNSET_SELECTED_FINDING = "UNSET_SELECTED_FINDING"; 